version: "3"
services:
  frontend:
    ports:
     - "5000:5000"
    build: ./front-end/.
  backend:
    ports:
     - "49153:8080"
    build: ./back-end/.
    environment:
     - "REDIS_HOST=redis"
     - "POSTGRES_HOST=postgres"
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=postgres"
     - "POSTGRES_DATABASE=postgres"
  redis:
    image: redis
    ports: 
     - "6379:6379"
  postgres: 
    image: postgres:latest
    environment: 
     - "POSTGRES_PASSWORD=postgres"
     - "POSTGRES_USER=postgres"
    restart: unless-stopped
    ports: 
      - 5432

