version: "3"
services:
  frontend:
    ports:
     - "5000:5000"
    build: ./front-end/.
  backend:
    ports:
     - "49154:8080"
    build: ./back-end/.
    environment:
     - "REDIS_HOST=redis"
  redis:
    image: redis
    ports: 
     - "6379:6379"
